name = "ratings"
compatibility_date = "2024-02-28"

# Entry point
main = "index.js"

[vars]
GITHUB_TOKEN = ""

[build]
command = "npm install"

[env.production]
routes = [
  { pattern = "ratings.decombust.workers.dev", custom_domain = true }
] 