name = "ratings"
main = "src/index.js"
compatibility_date = "2024-02-28"

[vars]
ENVIRONMENT = "production"

# Add your domain
[env.production]
routes = [
  { pattern = "ratings.decombust.workers.dev", custom_domain = true }
]

# Declare environment variable binding
[vars]
GITHUB_TOKEN = ""  # Value will be set in Cloudflare dashboard 