name = "ratings"
main = "index.js"
compatibility_date = "2024-02-28"

[vars]
ENVIRONMENT = "production"

# Add your domain
[env.production]
routes = [
  { pattern = "ratings.decombust.workers.dev", custom_domain = true }
]

# Configure secrets in the Cloudflare dashboard
# [secrets]
# GITHUB_TOKEN 