name = "ratings"
main = "src/index.js"
compatibility_date = "2024-02-28"

# Specify the entry point
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
GITHUB_TOKEN = ""  # Value will be set in Cloudflare dashboard

# KV Namespace binding
[[kv_namespaces]]
binding = "RATINGS_KV"
id = "YOUR_KV_NAMESPACE_ID"  # Replace with your actual KV namespace ID from Cloudflare dashboard

[triggers]
crons = []

# Add your domain
[env.production]
routes = [
  { pattern = "ratings.decombust.workers.dev", custom_domain = true }
] 