name = "ratings"
main = "src/index.js"
compatibility_date = "2024-02-28"

# Specify the entry point
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
GITHUB_TOKEN = ""  # Value will be set in Cloudflare dashboard

# KV Namespace binding
# IMPORTANT: You need to replace the ID below with your actual KV namespace ID
# from your Cloudflare dashboard (Workers & Pages > KV)
[[kv_namespaces]]
binding = "RATINGS_KV"
id = "761ce54f904d47fc89814421061362f2"  # Replace this with your actual KV namespace ID

[triggers]
crons = []

# Add your domain
[env.production]
routes = [
  { pattern = "ratings.decombust.workers.dev", custom_domain = true }
] 