name: Issue Creation

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Issue title'
        required: true
      body:
        description: 'Issue body'
        required: true
      labels:
        description: 'Issue labels (comma-separated)'
        required: false
        default: 'user-reported'

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = context.payload.inputs.labels.split(',').map(l => l.trim());
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: context.payload.inputs.title,
              body: context.payload.inputs.body,
              labels: labels
            });
