name: Process Ratings

on:
  repository_dispatch:
    types: [new_rating]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Process Rating
        run: python .github/scripts/process_ratings.py
        env:
          RATING_DATA: ${{ toJson(github.event.client_payload) }}
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add blend_data/
          git commit -m "Update ratings for ${BLEND_ID}"
          git push
        env:
          BLEND_ID: ${{ github.event.client_payload.blendId }} 